[package]
name = "cuteboard"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-htmx = "0.3.0"
actix-web = "4.8.0"
askama = "0.12.1"
askama_actix = "0.14.0"
askama_escape = "0.10.1"
ron = "0.8.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_derive = "1.0"