[phases.setup]
pkgs = ["pkg-config", "openssl", "openssl-dev", "libpq-dev"]

[phases.build]
cmd = "nix build .#nixpacks -o result"

[phases.start]
cmd = "./result/bin/cuteboard"

[environment]
RUST_LOG = "info"
