
name: Rust Build and Run

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 

    - name: Set up Rust
      uses: actions/setup-rust@v2  

    - name: Build Release
      run: cargo build --release 

    - name: Run Release
      run: ./target/release/cuteboard
